changes

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -15,6 +15,8 @@ available_secrets:
       env: GITHUB_TOKEN
     - versionName: projects/${_PROJECT_ID}/secrets/TEAMS_WEBHOOK_URL/versions/latest
       env: TEAMS_WEBHOOK_URL
+    - versionName: projects/${_PROJECT_ID}/secrets/TEAMS_WEBHOOK_FAILURE_URL/versions/latest
+      env: TEAMS_WEBHOOK_FAILURE_URL
 
 steps:
   
@@ -36,9 +38,9 @@ steps:
       - -c
       - |
         echo "📦 Pushing image..."
-        if ! docker push "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE_NAME}:$SHORT_SHA"; then
-          echo "Push failed" > /workspace/failure_marker
-        fi
+        echo "❌ Simulating push failure"
+        echo "Push failed" > /workspace/failure_marker
+        exit 1
 
   - id: Deploy
     name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
@@ -53,6 +55,7 @@ steps:
           --allow-unauthenticated \
           --service-account="${_SERVICE_ACCOUNT}" \
           --set-secrets="TEAMS_WEBHOOK_URL=TEAMS_WEBHOOK_URL:latest" \
+          --set-secrets="TEAMS_WEBHOOK_FAILURE_URL=TEAMS_WEBHOOK_FAILURE_URL:latest" \
           --set-secrets="GITHUB_TOKEN=GITHUB_TOKEN:latest"; then
           echo "Deploy failed" > /workspace/failure_marker
         fi
@@ -61,7 +64,7 @@ steps:
     id: Notify
     entrypoint: "bash"
     waitFor: ["Build", "Push", "Deploy"]
-    secretEnv: ['GITHUB_TOKEN', 'TEAMS_WEBHOOK_URL']
+    secretEnv: ['GITHUB_TOKEN', 'TEAMS_WEBHOOK_URL', 'TEAMS_WEBHOOK_FAILURE_URL']
     args:
       - -c
       - |
@@ -89,7 +92,7 @@ steps:
                     }
                 ]
               }" \
-          "$$TEAMS_WEBHOOK_URL"
+          "$$TEAMS_WEBHOOK_FAILURE_URL"
 
         else
         
@@ -171,103 +174,3 @@ steps:
               }" \
             "$$TEAMS_WEBHOOK_URL"
         fi
-
-  # - name: "ubuntu"
-  #   id: Notify
-  #   entrypoint: "bash"
-  #   waitFor: ["Build", "Push", "Deploy"]
-  #   secretEnv:
-  #     ["GITHUB_TOKEN", "TEAMS_WEBHOOK_URL", "TEAMS_WEBHOOK_URL_FAILURE"]
-  #   args:
-  #     - -c
-  #     - |
-  #       echo "📦 Installing curl jq..."
-  #       apt-get update && apt-get install -y curl jq git
-
-  #       echo "📣 Sending Teams notification..."
-  #       if [ -f /workspace/failure_marker ]; then
-  #         echo "❌ Failure detected. Sending failure message..."
-
-  #         curl -X POST -H "Content-Type: application/json" \
-  #           -d "$(cat <<EOF
-  #       {
-  #         "@type": "MessageCard",
-  #         "@context": "http://schema.org/extensions",
-  #         "summary": "Deployment Failure",
-  #         "themeColor": "FF0000",
-  #         "title": "❌ Deployment failed for BE '${_ENV}' environment",
-  #         "sections": [
-  #           {
-  #             "activityTitle": "Failure Details",
-  #             "text": "- **Environment**: ${_ENV}\\n- **Project**: ${_PROJECT_ID}\\n- **Service**: ${_SERVICE_NAME}\\n- **Version**: ${SHORT_SHA}"
-  #           },
-  #           {
-  #             "activityTitle": "Status",
-  #             "text": "Deployment Failed."
-  #           }
-  #         ]
-  #       }
-  #       EOF
-  #                 )" "$$TEAMS_WEBHOOK_URL_FAILURE"
-
-  #             else
-  #               COMMIT_SHA=$(git rev-parse HEAD)
-
-  #               echo "Fetching commit info..."
-  #               COMMIT_API="https://api.github.com/repos/MSN-EPIC/epic-be/commits/${COMMIT_SHA}"
-  #               COMMIT_DATA=$(curl -s -H "Authorization: token $$GITHUB_TOKEN" "$$COMMIT_API")
-  #               COMMIT_MESSAGE=$(echo "$$COMMIT_DATA" | jq -r '.commit.message')
-  #               COMMIT_AUTHOR=$(echo "$$COMMIT_DATA" | jq -r '.commit.author.name')
-
-  #               PR_API="https://api.github.com/repos/MSN-EPIC/epic-be/commits/$${COMMIT_SHA}/pulls"
-  #               PR_DATA=$(curl -s -H "Authorization: token $$GITHUB_TOKEN" -H "Accept: application/vnd.github.groot-preview+json" "$$PR_API")
-  #               PR_COUNT=$(echo "$$PR_DATA" | jq 'length')
-
-  #               if [ "$$PR_COUNT" -gt 0 ]; then
-  #                 PR_NUMBER=$(echo "$$PR_DATA" | jq -r '.[0].number')
-  #                 PR_TITLE=$(echo "$$PR_DATA" | jq -r '.[0].title')
-  #                 PR_SOURCE=$(echo "$$PR_DATA" | jq -r '.[0].head.ref')
-  #                 PR_TARGET=$(echo "$$PR_DATA" | jq -r '.[0].base.ref')
-  #                 PR_DESCRIPTION=$(echo "$$PR_DATA" | jq -r '.[0].body')
-  #                 PR_AUTHOR=$(echo "$$PR_DATA" | jq -r '.[0].user.login')
-
-  #                 PR_DESCRIPTION_FORMATTED=$(echo "$PR_DESCRIPTION" | sed 's/^/  /' | sed ':a;N;$!ba;s/\n/\\n/g')
-
-  #                 DETAILS="\n- **PR Title**: $${PR_TITLE}\\n- **PR Number**: #$${PR_NUMBER}\\n- **Branch**: $${PR_SOURCE} → $${PR_TARGET}\\n- **PR Description**:\\n$${PR_DESCRIPTION_FORMATTED}\\n- **PR Author**: $${PR_AUTHOR}"
-
-  #                 GIT_INFO_SECTION=$(cat <<EOF
-  #       {
-  #         "activityTitle": "PR Details",
-  #         "text": "$${DETAILS}"
-  #       },
-  #       EOF
-  #                 )
-  #               else
-  #                 GIT_INFO_SECTION=""
-  #               fi
-
-  #               echo -e "$${DETAILS}"
-
-  #               curl -X POST -H "Content-Type: application/json" \
-  #                 -d "$(cat <<EOF
-  #       {
-  #         "@type": "MessageCard",
-  #         "@context": "http://schema.org/extensions",
-  #         "summary": "Deployment Notification",
-  #         "themeColor": "00FF00",
-  #         "title": "✅ New version deployed to BE ${_ENV} environment",
-  #         "sections": [
-  #           {
-  #             "activityTitle": "Deployment Details",
-  #             "text": "- **Environment**: ${_ENV}\\n- **Project**: ${_PROJECT_ID}\\n- **Service**: ${_SERVICE_NAME}\\n- **Version**: ${SHORT_SHA}"
-  #           },
-  #           $${GIT_INFO_SECTION}
-  #           {
-  #             "activityTitle": "Status",
-  #             "text": "Deployment completed successfully."
-  #           }
-  #         ]
-  #       }
-  #       EOF
-  #                 )" "$$TEAMS_WEBHOOK_URL"
-  #             fi
